use_frameworks!

platform :ios, '8.0'

target 'ZZNetworking_Example' do
  pod 'ZZNetworking', :path => '../'

  target 'ZZNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
